### ISSUE TITLE
Make app keyboard accessible

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#270] opened 2022-06-27 21:48 UTC
It's currently not possible to use the app with a keyboard because there are no `:focus` states. So when you try to tab through the UI, the only feedback you get is sometimes seeing the cursor in an input field.

Besides the fact that developers love using their keyboards to navigate things, it's also a standard accessibility thing!

**Comment by sebastinez** [comment] 2022-07-29 07:50
Hey @brandonhaslegs have you had any progress on this? Else would like to take a stab at it.

**Comment by brandonhaslegs** [comment] 2022-07-29 07:58
Go for it! Feel free to do anything I have assigned to myself.

**Comment by rudolfs** [comment] 2022-12-22 16:15
Duplicate of https://github.com/radicle-dev/radicle-interface/issues/300.

**Closed by rudolfs** 2022-12-22 16:15 UTC
Labels: ux
