### ISSUE TITLE
Module preloading

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#479] opened 2022-11-08 12:59 UTC
I'll write an issue wrt this, since it's something conceptual for now, which we should have a discussion about.

It originated on the router PR as:
`would be cool if we could do navigate('/foo', ModuleName, { preload: true }) or something`

Currently I'm studying how we could implement some abstraction over the general modules to allow this.
Feel free to post your ideas, or suggestions

**Comment by rudolfs** [comment] 2023-05-15 09:15
Could you please clarify if this issue is about data pre-loading in a view or whether it's about pre-loading the js/ts imports for a certain route? Could you also elaborate what's the underlying problem that we're trying to solve? If it's about import loading, is the actual issue page load speeds and the volume of data that the app transfers?

**Comment by sebastinez** [comment] 2023-05-15 14:52
Hey @rudolfs, yeah the original idea behind this issue was to allow the preloading of Svelte Components.

This would allow us to load a component into the browser, and then when navigating to it we would be able to provide a quicker render instead of an eventual blank page and loading spinners.

**Comment by rudolfs** [comment] 2023-05-15 14:55
So is this a duplicate of https://github.com/radicle-dev/radicle-interface/issues/668?

**Comment by rudolfs** [comment] 2023-05-15 17:09
So this is about SSR then?

**Comment by sebastinez** [comment] 2023-05-16 21:09
I don't think we want to add SSR but in the end everything converges to a snappy app like UX

**Comment by rudolfs** [comment] 2023-05-17 06:38
> I don't think we want to add SSR but in the end everything converges to a snappy app like UX

Ok, then I think this will be covered once I convert the remaining project view to the pre-loader that we have in the router. So #667 and https://github.com/radicle-dev/radicle-interface/pull/767 should cover this.

**Closed** 2023-05-17 08:03 UTC
Labels: tech debt
