### ISSUE TITLE
Non-functional Sign in button on seed node page

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#264] opened 2022-06-27 20:33 UTC
There's a button, I am signed in, clicking the button does nothing. Not sure why it's there, but it doesn't work. 

- [ ] Make the button work
- [ ] Explain what seed management is and what you can do if you sign in
- [ ] Add tooltip to button

<img width="490" alt="image" src="https://user-images.githubusercontent.com/4406983/176030090-a4d3f55a-5c47-4a04-8ce2-eee7338564fe.png">

**Comment by sebastinez** [comment] 2022-06-28 07:50
This is the SIWE sign in button, which currently is just that, in the future you'll be able to do administrative tasks on your seed node through the interface, once signed in.
I think the explanation shouldn't be here, but in docs.radicle or somewhere more suited.
In your case it's an issue with an updated interface vs. a non updated http-api.
Here you can see a working example https://app.radicle.network/seeds/seed.sebastinez.dev

I'm thinking we should do a feature check and if the http-api doesn't have the SIWE endpoints hide the button?
wdyt @cloudhead

**Comment by sebastinez** [comment] 2022-07-01 11:38
> @sebastinez When I try to connect here, I get the confirmations in my wallet but when I confirm them, nothing happens in the UI. Just a loading animation, then nothing. 

Hmm weird, I just tried it, and it works fine. Have you tried to do it on app.radicle.network and on my seed, the link I posted in my last comment?
Also I did some changes to my seed so maybe you tried at some point that wasn't ideal. But should work now

**Comment by brandonhaslegs** [comment] 2022-07-01 11:53
Yep. Here's what I didhttps://user-images.githubusercontent.com/4406983/176889477-95524dab-0bcc-49a0-bdcf-f4d6c5e7c46b.mp4

**Comment by cloudhead** [comment] 2022-07-01 14:34
The tooltip could just say "Sign in to manage this seed node".

I think the first use-case we'll have for this feature though is signing in to your local node to be able to create issues and comment, but we're not there yet and right now you can't do anything after you sign-in. I'd be ok with feature-flagging it also behind a config var until we start building that functionality into the seed node :shrug:

**Comment by sebastinez** [comment] 2022-07-01 21:13
> Wasn't there an issue with walletconnect signing? or did we fix that?

Yeah I think the issue was that walletconnect did not let us sign the plain text SIWE message.. But I will take a look at workstreams where it seems to work..

**Comment by sebastinez** [comment] 2022-07-21 11:59
Ok I'm not able to reproduce it anymore.. Could you maybe check if it's still not working @brandonhaslegs?

**Comment by sebastinez** [comment] 2022-12-22 10:25
Closing this issue since siwe has been removed with #534

**Closed by sebastinez** 2022-12-22 10:25 UTC
Labels: design
